### ISSUE TITLE
Help: Missing or wrongly named options fil

### ISSUE THREAD

**Issue by jelsdorf** [aleenprd/boligportal-scraper#4]
Hi Aleenprd,

Great work with the scraper.

However, I am having issues getting main.py to work. I have installed all the neccesary packages, however I get the following error:

"--mode scrape
*
Missing or wrongly named options file.

Missing, empty or wrongly named scraping config file.                 Program will terminate."

I have not altered the config files naming nor folder placement. I just wanted to get it working before messing with any filters etc.

Can you help?

Thanks a lot.

**Comment by aleenprd** [comment]
Hey!

Thanks for the feedback. I will take a look at it tonight and come back to
you.

But when you are running main.py, you need to make sure your current
working directory is the 'src' file. I think that should solve it for you.

**Comment by jelsdorf** [comment]
Thank you!! That did the trick! I am still very new to Python, but have some experience in R from Uni, so still learning the ropes :).

**Comment by jelsdorf** [comment]
Would omitting the 'summary' column and google translate function speed up the scraping time?

**Comment by jelsdorf** [comment]
Just a last thing: It seems it only returns the first 18 listings i.e. the first page of the search url. Do I need to define a range of pages or should it work as is by scraping all pages on the specified url?

**Comment by aleenprd** [comment]
Read the readme
